### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by Etanarvazac** [MrDiamond64/Scythe-AntiCheat#14]
I saw your pack description states killing NPC's. Is this a default thing, or can it be turned off (my realm utilizes NPC's)?

Is Gametest required for the pack to run? Or can the features without that toggle run independantly?

**Comment by MrDiamond64** [comment]
> Will it kill the current NPC's prior to using that function? If so, is there a way to disable it prior to adding?

If your using the latest version then it should be disabled by default

**Comment by Etanarvazac** [comment]
Okay. Thank you.
