### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by iEmreTRi** [MrDiamond64/Scythe-AntiCheat#15]
my name is emre Omelet arcade Can I translate in Turkish and use ScytheAnti-CheaTs please accept I promise to share only omelete arcade I wrote your Mod 
Developed Scythe I wrote it down as
![Screenshot_2022-03-21-20-31-22-532_com mojang minecraftpe](https://user-images.githubusercontent.com/102467463/160280114-27f36cb6-b9ea-4272-86d4-6b7264693b30.jpg)
I just edit and I want to add function I want to get permission from you when I do this /function tools/credits I just edit and I want to add function I want to get permission from you when I do this /function tools/credits Scythe. I added name Mod Developer as you can see If I'd written your name, they wouldn't have found you.
I share Github Link I say your name thank you everyone very much https://omlet.gg/r/dPKj9I0EmbWzHSkEx
You can look at it here. I promise to share it just here ♥️🥺 All minecraft Hack There's Google Play Tolboox  for Protection :+1: ✨:(

**Comment by m-doescode** [comment]
Sorry, I'm having a hard time understandig what you mean. So I'm guessing you said:
1. You translated the addon into Turkish
2. You want to distribute it
3. You credited MrDiamond64

You should be able to do this just fine according to the license, however you must make your fork open source. E.g. by uploading it to github. You must also include the same license.

But it is MrDiamond64's project after all so I'm going to wait to see what they say.

**Comment by iEmreTRi** [comment]
No Just omelette arcade I'll share

**Comment by iEmreTRi** [comment]
Do you allow it?

**Comment by m-doescode** [comment]
> Do you allow it?

You'll have to ask @MrDiamond64 and wait for them to respond.

**Comment by iEmreTRi** [comment]
> > izin veriyor musun
> 
> @MrDiamond64'e sormanız ve yanıt vermelerini beklemeniz gerekecek .

Can you ask me if I signed up on Github today

**Comment by MrDiamond64** [comment]
Hi,

You are allowed to do this as long as I get credited.

**Comment by iEmreTRi** [comment]
> 

Thank you very much 🥺✨🥰♥️

**Comment by MrDiamond64** [comment]
I have received word that you are selling the Anticheat addon for Omlet Arcade Tokens. I do not want it to be sold.

**Comment by iEmreTRi** [comment]
JT It's not working for us JT It's not money JT I got it for jt team Jt Only works to change names and features such as frames It's noJT It's not working for us JT It's not money JT I got it for jt team Jt Only works to change names and features such as frames It's not real money He's my told you JT I'm just using it to change the name for my teamer JT for My Efforts t real money He's my told you JT I'm just using it to change the name for my teamer JT for My Efforts

**Comment by iEmreTRi** [comment]
It's not real money I'm just using it for a name change

**Comment by AngelOfDarkness728** [comment]
its still marked as selling.

**Comment by iEmreTRi** [comment]
> hala satış olarak işaretli.

This person is my enemy He shared your project by making Vulcan https://omlet.gg/r/dAc8qILb_En3lojKn

**Comment by AngelOfDarkness728** [comment]
i gave all credits. and didnt sell it.

**Comment by iEmreTRi** [comment]
> tüm kredileri verdim. ve satmadı.

You Didn't Write Scythe, You Didn't Add a Link Anywhere, You Shared It Like You Did It Yourself

**Comment by AngelOfDarkness728** [comment]
stop arguing with me on a issue.
never shared it by the comment : "i made it"

**Comment by iEmreTRi** [comment]
> Benimle bir konu hakkında tartışmayı bırak. onu asla şu yorumla paylaşmadım: "Ben yaptım"

YOU POSTED FAKE UI MAKE

**Comment by AngelOfDarkness728** [comment]
bro fix your english fr
i only added an title.
didnt say i made it lol.

**Comment by iEmreTRi** [comment]
> kardeşim ingilizceni düzelt fr sadece başlık ekledim lol yaptım demedim

![IMG_20220327_192215](https://user-images.githubusercontent.com/102467463/160290982-598d801a-9498-43da-af6f-98135ab56022.jpg)

**Comment by AngelOfDarkness728** [comment]
What Do You Mean?
You Stole And Sold It And Tryina Expose Me By Fake Pictures? Nice I Guess.
I Wonder What's The Difference Between These 2 Pictures Lol.

**Comment by iEmreTRi** [comment]
Editing Other People's Modes and Sharing Them As Mine 

> Ne demek istiyorsun? Onu çalıp sattın ve beni sahte fotoğraflarla ifşa etmeye mi çalışıyorsun? Güzel Sanırım. Bu 2 Resim Arasındaki Fark Nedir Merak Ediyorum Lol.

**Comment by AngelOfDarkness728** [comment]
I Never Shared Them As Mine Also Any Proof I Said "Its Mine"?
Also What Did You Do Make All Of The Anti-Cheat Yourself, You Also Edited It.

**Comment by iEmreTRi** [comment]
You let me. @MrDiamond64 Whatever I Do JT token I didn't make real money after all I'm just sharing an omelete arcade And I added Everywhere you can name it And the link name Scythe. Added link https://github.com/MrDiamond64/Scythe-AntiCheat

**Comment by AngelOfDarkness728** [comment]
He Said He Doesnt Want It To Be Sold.
Please Stop Arguing, Its Still Selling Real Money Or Not Doesnt Matter.

**Comment by iEmreTRi** [comment]
> Satılmasını İstemediğini Söyledi. Lütfen Tartışmayı Bırakın, Hala Satıyor, Gerçek Para Olup Olmaması Önemli Değil.
Don't Get Involved Who Are You?

**Comment by AngelOfDarkness728** [comment]
Still Selling, Doesnt Matter If You Credit Please Stop Arguing Now.

**Comment by iEmreTRi** [comment]
> Hala Satıyor, Kredi Alırsanız Önemli Değil Lütfen Şimdi Tartışmayı Bırakın.

I say who are you you can't say anything I've worked my project who are you fuck go

**Comment by AngelOfDarkness728** [comment]
Sure Then Buddy Get More Mad.
I Release The Argument To @MrDiamond64 .

**Comment by MrDiamond64** [comment]
> i gave all credits. and didnt sell it.

Looking through the Vulcan Omlet Arcade page I wasn't able to find any credit in the post.
