### ISSUE TITLE
How can we contact you?

### ISSUE THREAD

**Issue by MrRazamataz** [MrDiamond64/Scythe-AntiCheat#17]
Is there some way I can contact you on discord or something similar? I am the CMO at WitherHosting and we were interested if you were interested in some form of partnership/sponsorship of this project.

**Comment by adgods1** [comment]
join the discord

**Comment by m-doescode** [comment]
According to #11, it is available here: https://discord.gg/TGFqX4t8

**Comment by MrDiamond64** [comment]
You can contact me from my discord server. https://discord.gg/FyuR9nTx

**Comment by MrRazamataz** [comment]
Thank you
