### ISSUE TITLE
Can we use the safe beehive and bee_nest?

### ISSUE THREAD

**Issue by nakanotti** [MrDiamond64/Scythe-AntiCheat#18]
Unfortunatly, Nearby beehives are always removed.

I'm doing it like this...
<functions/main.mcfunction>
```
   6: execute @s[tag=!op] ~~~ function checks/cbe
   7: execute @s[tag=!op] ~~~ function checks/illegalitems
```
(add "op" tag to safe player.)

Is there a better way?

**Comment by MrDiamond64** [comment]
All cbe.mcfunction does is clear out any nearby beehives and bee nests. Your method would work the best.

**Comment by nakanotti** [comment]
Okay, I change it to a "safe" tag and assign it to a trusted player.
Thank you for your answer.
