### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Snowpuff** [MrDiamond64/Scythe-AntiCheat#19]
So someone put a command block with the command say in my realm and I can’t find it, do you think you could add a feature where it clears or finds the command block, also can you make a full guide to all the functions and how to use them. One last thing, can u add a way to change players names like UAC does

**Comment by MrDiamond64** [comment]
> add a feature where it clears or finds the command block

This already exists. It can be enabled by doing `/function settings/removeCommandBlocks` or `!removecommandblocks`

> also can you make a full guide to all the functions and how to use them

https://github.com/MrDiamond64/Scythe-AntiCheat/wiki/Additional-Commands
it is kinda outdated though.

**Comment by Snowpuff** [comment]
Ok thanks,
