### ISSUE TITLE
BadEnchantA Bug! 

### ISSUE THREAD

**Issue by JorosTheModderPH** [MrDiamond64/Scythe-AntiCheat#23]
I simply held the sharpness 1 iron sword and it said BadEnchantA.
It's sharpness 1 is ilegal?

![Screenshot_20220429_203908_com mojang minecraftpe](https://user-images.githubusercontent.com/83757828/165947047-c44dbe91-f768-4b63-811f-aceed00a8a7a.jpg)

**Comment by JorosTheModderPH** [comment]
Iron Sword with Sharpness 1

**Comment by MrDiamond64** [comment]
Can you send a video of you picking up the iron sword up and it getting flagged? I have tested it on a local world and it works just fine.

**Comment by JorosTheModderPH** [comment]
https://youtu.be/Nbu4ci_UFdQ
I can't upload the video here, but I uploaded it on YouTube instead.
 
My minecraft version is 1.18.30 but I updated it to 1.18.31.

**Comment by MrDiamond64** [comment]
Unable to reproduce.
https://streamable.com/q77lr9

Have you messed around the `config.js` file by any chance?

**Comment by JorosTheModderPH** [comment]
I didn't mess the config.js.

**Comment by Mantou1233** [comment]
maybe try to reinstall the anti-cheat and see does the problem still ensist.

**Comment by JorosTheModderPH** [comment]
I did but it still not working.

**Comment by JorosTheModderPH** [comment]
Nevermind i fix it

**Comment by JorosTheModderPH** [comment]
@MrDiamond64 I think you forgot to put "minLevel": 0, in config.js line 221 since you released the addon.

**Comment by JorosTheModderPH** [comment]
I double checked it and I found out why it's not working.

**Comment by MrDiamond64** [comment]
> @MrDiamond64 I think you forgot to put "minLevel": 0, in config.js line 221 since you released the addon.

Already fixed in commit https://github.com/MrDiamond64/Scythe-AntiCheat/commit/705ea8430e97ee4767350725733f2a3e381991a5
