### ISSUE TITLE
Gametest commands isn't working

### ISSUE THREAD

**Issue by ZephyrX10** [MrDiamond64/Scythe-AntiCheat#34]
The gametest commands isn't working for me when i use it in my aternos server

**Comment by MrDiamond64** [comment]
Make sure Gametest framework is enabled in world settings.

**Comment by ZephyrX10** [comment]
I already enable it but it doesn't work on aternos

**Comment by MrDiamond64** [comment]
> I already enable it but it doesn't work on aternos

Aternos probably has Gametest disabled as you can create 24/7 servers.
