### ISSUE TITLE
boats Are Unusable.

### ISSUE THREAD

**Issue by PolyframeX** [MrDiamond64/Scythe-AntiCheat#40]
When Attempting To Ride A Boat, The Player Immediatly Gets Teleported Outside Of It.

**To Reproduce**
1. Go to 'Download The Pack Onto A World
2. Create A Boat
3. Attempt To Ride It

**Expected behavior**
Boats Should Be Rideable

**Additional context**
Not Sure If This Is Intentional, If It Is Is There Any Way To Disable It?

**Comment by MrDiamond64** [comment]
Can you send a video of the issue occuring? Make sure you have the `notify` tag applied to yourself.

**Comment by PolyframeX** [comment]
For some reason the error stopped? I am not sure why.

**Comment by MrDiamond64** [comment]
Ive managed to replicate this issue and fixed it with f49e5b84588a6b517aa7ee571a91bb8b428e182e. If this bug occurs again then just send a video of it happening.

**Comment by PolyframeX** [comment]
The bug is still occuring with bad packets.
![image](https://user-images.githubusercontent.com/80133652/180853967-80cf25b2-0274-4d74-a4fb-4891f968c64c.png)

**Comment by PolyframeX** [comment]
In the meantime, is there anyway to disable bad packets till this is fixed?

**Comment by MrDiamond64** [comment]
> In the meantime, is there anyway to disable bad packets till this is fixed?

You can disable the BadPackets[1] check in config.js or use the newest commit which uses the old check.
