### ISSUE TITLE
Most GUI Does Not Work.

### ISSUE THREAD

**Issue by PolyframeX** [MrDiamond64/Scythe-AntiCheat#42]
All GUI Does Not Work Besides The Player Menus And Submenus Within Them

**To Reproduce**
1. Type In !gui in chat
2. Right Click On The Axe Giving To You
3. Attempt To Access Any Gui Menus

**Expected behavior**
Menus Should Open

**Screenshots**
https://drive.google.com/file/d/1xzyboYWYHn7bytK-Xkew69Jflv1Pohxj/view?usp=sharing

**Comment by MrDiamond64** [comment]
This is intentional as i have not yet finished them yet.
