### ISSUE TITLE
CPS Autoclicker False Detections

### ISSUE THREAD

**Issue by PolyframeX** [MrDiamond64/Scythe-AntiCheat#43]
The CPS keeps claiming that 15 or 20 CPS is from a autoclicker, when in reality my friends are just jitter clicking.

**To Reproduce**
1. Turn On Notifications
2. Try Getting 15-20 CPS
3. See Message

**Expected behavior**
CPS Detetection Should Detect Maybe 25 or 30 Cps.

**Screenshots**
![image](https://user-images.githubusercontent.com/80133652/181142381-6ce9cb2e-6344-49e0-a82c-22c28bcd5ec5.png)

**Comment by MrDiamond64** [comment]
Nothing i can really do about it as all it does is check if you have too high CPS.

> CPS Detetection Should Detect Maybe 25 or 30 Cps.
This solution is not viable at all. Minecraft registers attacks once every tick, and a tick occures 20 times a second. The maximuim cps the server can register per second is 20.
