### ISSUE TITLE
Custom mobs get despawned

### ISSUE THREAD

**Issue by MeteoroidShot** [MrDiamond64/Scythe-AntiCheat#45]
i have a small add-on where it spawns a mob using an item after u right click on it , the anticheat kills it instantly instead and doesn't give any warnings , any help?

**Comment by MrDiamond64** [comment]
Does the item namespace end with "_spawn_egg"?

**Comment by MeteoroidShot** [comment]
Yes it does

**Comment by MrDiamond64** [comment]
> Yes it does

line 251 at ./scripts/data/config.js

Disable anti-spawn eggs by replacing "true" with "false"
