### ISSUE TITLE
Kick

### ISSUE THREAD

**Issue by Dream23322** [MrDiamond64/Scythe-AntiCheat#47]
So you can autoban players but it would be nice to be able to have a setting where it only auto kicks and not auto bans, a bit like radon anticheat, auto kicks for a certain amount of times before ban.

**Comment by MrDiamond64** [comment]
For the most part this is already implemented.

In the config.js file, you can customize if each check should ban, kick or do nothing, and customize how much violations are needed until an autoban.

**Comment by Dream23322** [comment]
i have tried that but when i change the file extention back to mcpack from .zip it reverts back
