### ISSUE TITLE
Anti Phase

### ISSUE THREAD

**Issue by Dream23322** [MrDiamond64/Scythe-AntiCheat#48]
So, unless im missing something this anticheat doesnt have an anti phase system. so, i figured out if you do this with a repeating command block: execute @a~ ~ ~ detect ~ ~1 ~ dirt 0 /tag @s add phase : it will detect  if someone phases through dirt, if you had this repeating constantly in the anticheat with nearly every block it would be an anti phase system, you can always change what it does, like instead of adding a tag it kicks the player

**Comment by MrDiamond64** [comment]
Scythe used to have an anti-phase but it was later removed due to false positives and unnecessary lag it requires to check every block.

unrelated, but you accidentally pinged 2 GitHub account :p
