### ISSUE TITLE
No safe

### ISSUE THREAD

**Issue by Dream23322** [MrDiamond64/Scythe-AntiCheat#49]
so befire when you told me i can go into the config file and change what happens, it just reverts when i change back to the .mcpack, am i doing something wrong? i change the file extention is that the wrong thing to do?

**Comment by MrDiamond64** [comment]
You dont seem to be doing anything wrong. Make sure to delete the old Scythe from both your world and in Settings > storage.

**Comment by Dream23322** [comment]
yeah i am doing that but it still doesnt work
it only bans, can you send me a version that auto kicks but not bans? and all modules are on, (fly-a and other)
thanks
