### ISSUE TITLE
Cant make myself "Scythe-Opped" 

### ISSUE THREAD

**Issue by SysAdminDoc** [MrDiamond64/Scythe-AntiCheat#53]
I am trying to set this up, I own this realm but cannot manage to exempt myself from the anti-cheat or make myself OP.

![image](https://user-images.githubusercontent.com/54586742/185222998-16c3a030-b76d-4428-9db3-567a98b3fef4.png)

**Comment by MrDiamond64** [comment]
Run **/function op**

**Comment by SysAdminDoc** [comment]
> Run **/function op**

That worked, I wish this were in the wiki for noobs like me. Thank you.

**Comment by MrDiamond64** [comment]
Your welcome.
