### ISSUE TITLE
Compatible Versions

### ISSUE THREAD

**Issue by AdolfDuckler** [MrDiamond64/Scythe-AntiCheat#6]
Can you please tell us what version the ACs are compatible with? I need one for mcpe 1.18.2 or just 1.18 supports.

**Comment by GlitchyTurtle** [comment]
It should work with 1.18.2 as well.

**Comment by AdolfDuckler** [comment]
I tried ir, But some of the Features are missing.

**Comment by GlitchyTurtle** [comment]
That could be because you don't have game test on, something else. Are all the settings the same as when it was working?

**Comment by AdolfDuckler** [comment]
Maybe, Thanks for the advice. I appreciate it.

**Comment by MrDiamond64** [comment]
> Can you please tell us what version the ACs are compatible with? I need one for mcpe 1.18.2 or just 1.18 supports.

1.18 1.18.1 and 1.18.2 should all work with no issues. Like GlitchyTurtle said, you will need gametest enabled for the full feature set.
