### ISSUE TITLE
Crash type 2 on horion client

### ISSUE THREAD

**Issue by jameshackerbond** [MrDiamond64/Scythe-AntiCheat#61]
**Describe the bug**
On horion there is a crasher and they added an option for the crasher for a type 2 and type 1 (type 1 is the invaild movement, type 2 is unknown and dosent use invaild movement.)

**To Reproduce**
1. Inject horion and go on a world with scythe
2. go to clickgui and right click on crasher then select type 2
3. After doing all of that enable crasher and it will crash your game also bypassing scythe's anticheat

**Expected behavior**
It should stop the world from crashing

**Screenshots**
busy rn I'll add them later

**Additional context**
Please fix this fast players are crashing my skygen

**Comment by jameshackerbond** [comment]
# Please dont make me use UAC ;(

**Comment by MrDiamond64** [comment]
I know exactly how the type 2 crash works.

Only one issue. There is unfortunately no way to detect it with addons.

**Comment by jameshackerbond** [comment]
💀
