### ISSUE TITLE
Allow Scythe OPs to used hacked items

### ISSUE THREAD

**Issue by SysAdminDoc** [MrDiamond64/Scythe-AntiCheat#63]
I wish to be able to disable this anti-cheat to allow myself to use cheats from Horion.

**Comment by jameshackerbond** [comment]
what about allow people with the tag op to use illegalitems, just not spawn eggs or anything cbe related (or add like an illegals whitelist to not trigger the anticheat such as the end gateway block or nether reactor core.)
