### ISSUE TITLE
Anti cheat not working.

### ISSUE THREAD

**Issue by AdolfDuckler** [MrDiamond64/Scythe-AntiCheat#7]
Im using Mcpe 1.18.2 with Experimantals on.

The Speed, Jesus, Fly (buggy), High Jump, Tap teleport, Phase, Noclip. Doesn't work as expected... The fly does work for a bit and never again, I used "Toolbox for Minecraft PE" (its the name) i tried multiple hacks and it didn't work. Other features such as "/function tool/fly" Doesn't exist on the function lists while on game.

Is it compatible for 1.18 version?

**Comment by MrDiamond64** [comment]
> The Speed, Jesus, Fly (buggy), High Jump, Tap teleport, Phase, Noclip. Doesn't work as expected... The fly does work for a bit and never again, I used "Toolbox for Minecraft PE" (its the name) i tried multiple hacks and it didn't work

The problem with command-blocked based anticheats is that it cannot do as much. The Phase check can only detect certian blocks, if we were to make it detect all blocks the tps will go down.

We could detect speed using gametest, however Server Authoritative Movement makes it so it reports normal speeds. The other hacks you mentioned cannot be detected as of now

> Other features such as "/function tool/fly" Doesn't exist on the function lists while on game.
You need to enable education edition in your world settings.

> Is it compatible for 1.18 version?
Yes it is.

**Comment by AdolfDuckler** [comment]
Thank you for the reply, This is helpful since a server of mine is bombarded by hackers so we're trying to find free but effective ACs... Thanks for the help!
