### ISSUE TITLE
What is it and why is it here?

### ISSUE THREAD

**Issue by JKearnsl** [MrDiamond64/Scythe-AntiCheat#72]
https://github.com/MrDiamond64/Scythe-AntiCheat/blob/b466f542a68686b4f95d935360ac82107270fcf4/scripts/main.js#L19

Why are messages containing "the best minecraft bedrock utility mod" or "disepi/ambrosial" being cancelled?

This is ridiculous. Your anti-cheat shouldn't care about this.

**Comment by MrDiamond64** [comment]
These are messages that Horion and Zephyr spammer modules send by default.

**Comment by JKearnsl** [comment]
You are too attached to them, don't you think?

I think your anti-cheat should not be responsible for this, it should be done by the administrator, unless he really needs this message to be in the chat.
The task of your anti-cheat as an anti-spammer is to check the delay between messages.

Just understand, all these js routines are very slow. Extra lines make your anti-cheat slow

**Comment by adgods1** [comment]
bro stfu no one asked

**Comment by adgods1** [comment]
You have a hentai API now be quiet

**Comment by JKearnsl** [comment]
> You have a hentai API now be quiet

Did I ask you, child? Your time has not yet passed, take a rest :)

**Comment by Tarvey** [comment]
> You have a hentai API now be quiet

didn't you get exposed as a pedo?
