### ISSUE TITLE
Hey USSR bro my discord account disabled! {!-Please Read-!}

### ISSUE THREAD

**Issue by StrafeYourself** [MrDiamond64/Scythe-AntiCheat#73]
Hey USSR,
StrafeYourself here,
Yesterday I was making a battle arena with my realm, and I randomly got logged out of my account. I look at my emails and it said my account was disabled by discord. I wish I could just create a new discord, but it asks for my phone number every signal and since we can only use 1 phone number per discord account that means when I type my number in the new account that means the number that I typed into the new account will get disabled. Meaning I might never get to see you again! However, I felt bad for what I said, and I did an appeal that took hours, so I really hope it pays off and I get to see all of my amazing friends and people that I met and have had fun times with again. If not, USSR I just want to let you know I will really miss you, And I enjoyed all the time we have spent together. But the thing I will miss the most is your kind amazing helpful personality! Good Bye USSR Thanks For Everything!

Sincerely Your Best Friend StrafeYourself .😢

**Comment by MrDiamond64** [comment]
OMG wtf bro 😭

**Comment by StrafeYourself** [comment]
Bro sorry if I can get in contact with you again! I will! I miss you already! 😭

**Comment by GreatNate0509YT** [comment]
That sounds sad :/

**Comment by StrafeYourself** [comment]
It is bro! ;(

**Comment by GreatNateDev** [comment]
Change ur number?
