### ISSUE TITLE
fastuseA error

### ISSUE THREAD

**Issue by JKearnsl** [MrDiamond64/Scythe-AntiCheat#74]
https://github.com/MrDiamond64/Scythe-AntiCheat/blob/2ea51c0d1ecb82bf12f7766e0b8cdeb636f0d9e9/scripts/main.js#L769

Mistake. This is not in the config: `config.modules.fastuseA.use_delay`

https://github.com/MrDiamond64/Scythe-AntiCheat/blob/2ea51c0d1ecb82bf12f7766e0b8cdeb636f0d9e9/scripts/data/config.js#L485-L491

**Comment by MrDiamond64** [comment]
Thanks for reporting, the issue has been fixed.
