### ISSUE TITLE
Leaving cheats disabled?

### ISSUE THREAD

**Issue by SysAdminDoc** [MrDiamond64/Scythe-AntiCheat#76]
Just adding a quick question if it is possible to use this without enabling cheats? I want to keep achievements enabled but cannot do that if I need to enable cheats in order to properly load this anti-cheat.

**Comment by GreatNate0509YT** [comment]
Just got an idea try adding it via the Mc files instead of the game go into ur world folder behavior packs place the anticheat in it load up the world and see if it worked and if achievements are still on but if it works u won't be able to use most of the anti cheat bc no command perms

**Comment by PolyframeX** [comment]
This shouldn't be a issue within the Scythe Anticheat GitHub, this issue is impossible to fix without modifying the game with an outside editor. and Scythe can't do anything about this.
