### ISSUE TITLE
Gametest is disabled even when gametest is enabled by default

### ISSUE THREAD

**Issue by bozogithubbozo** [MrDiamond64/Scythe-AntiCheat#80]
i enabled **education edition and Beta APIs + Next Major Update** and the error still appears and how to fix? Help me

**Comment by bozogithubbozo** [comment]
@MrDiamond64

**Comment by MrDiamond64** [comment]
> i enabled **education edition and Beta APIs + Next Major Update** and the error still appears and how to fix? Help me

- make sure scythe is at the top of the behavior packs list
- make sure scythe supports the version of mc you are using
- if the first 2 things are fine, do `/scoreboard players set scythe:config gametestapi 1`

**Comment by bozogithubbozo** [comment]
Thank you
