### ISSUE TITLE
Hey, add whitelist that doesnt flag people as cheating

### ISSUE THREAD

**Issue by bozogithubbozo** [MrDiamond64/Scythe-AntiCheat#84]
Hey, me and friend wanted to make smp but both of me uses client that are hacking

Please add whitelist to your anticheat

Have a good day

@MrDiamond64

**Comment by MrDiamond64** [comment]
This already exists, edit config.js file in the addon. Also, please dont mention me.

**Comment by bozogithubbozo** [comment]
Oh sorry
Dear diamond

**Comment by bozogithubbozo** [comment]
also diamond, how do i whitelist 2 peoples? diamond
