### ISSUE TITLE
Hey, How to whitelist 2 peoples for my realm

### ISSUE THREAD

**Issue by bozogithubbozo** [MrDiamond64/Scythe-AntiCheat#87]
Hey...

I wanted to whitelist my friend and myself for my realm
but it's really hard

Please help me

**Comment by bozogithubbozo** [comment]
Please
Please
Please
Please
Please

**Comment by bozogithubbozo** [comment]
@MrDiamond64 pls

**Comment by bozogithubbozo** [comment]
@MrDiamond64 wake up

**Comment by MrDiamond64** [comment]
stop annoying me

**Comment by bozogithubbozo** [comment]
@MrDiamond64 when will u help me?😡😡

**Comment by bozogithubbozo** [comment]
goofy ahh people wont help me
