### ISSUE TITLE
InvalidSprint glitch , works by itself even with no blindness effect , only fixes itself if player has speed/etc please help

### ISSUE THREAD

**Issue by MeteoroidShot** [MrDiamond64/Scythe-AntiCheat#9]
**Describe the bug**
InvalidSprint/A gives alerts when the player is sprinting without the blindness effect.

**To Reproduce**

**Expected behavior**
No false flags.

**Screenshots**

**Additional context**

**Comment by MeteoroidShot** [comment]
![image](https://user-images.githubusercontent.com/74373408/150654725-2538f8e5-a199-4cda-8ed6-4a607e2b8ed1.png)

**Comment by MrDiamond64** [comment]
Is the behaviour pack on the top of the addons list?

**Comment by MeteoroidShot** [comment]
Yep it’s activated on a realm too

**Comment by MeteoroidShot** [comment]
> Is the behaviour pack on the top of the addons list?

Yep it’s activated on a realm too

**Comment by MeteoroidShot** [comment]
> Is the behaviour pack on the top of the addons list?

- Is there a way to completely disable invalidsprint?

**Comment by MrDiamond64** [comment]
> > Is the behaviour pack on the top of the addons list?
> 
>     * Is there a way to completely disable invalidsprint?

Delete the `functions/checks/alerts/invalidsprint.mcfunction` file and set 
`
"invalidsprintA": {
            "enabled": true
        },
`
to
`
"invalidsprintA": {
            "enabled": false
        },
`
in `scripts/data/config.js`

**Comment by MeteoroidShot** [comment]
Thank you
